const base = {
  accent: '#2d65ed',
  blue: '#315a8d',
  blueDeep: '#14253d',
  iceTint: '#e8eef4',
  ink: '#0b1320',
  inkSoft: '#50647c',
  paper: '#f8fafc',
  steel: '#8ea2b8',
  white: '#ffffff',
} as const;

export const nativeTokens = {
  dark: {
    action: base.blue,
    actionPressed: '#3b6ba4',
    border: '#2b3c50',
    danger: '#ff838b',
    dangerSurface: '#431d27',
    focus: '#6e9aff',
    info: '#83a8ff',
    infoSurface: '#1b3047',
    success: '#63bea8',
    successSurface: '#14362f',
    surface: '#08111f',
    surfaceMuted: '#18273a',
    surfaceRaised: '#101c2c',
    text: '#f7f9fc',
    textMuted: '#a8b6c7',
    warning: '#e6ad63',
    warningSurface: '#3d2a12',
  },
  light: {
    action: base.blueDeep,
    actionPressed: '#0f1f35',
    border: '#d9e1ea',
    danger: '#b4232f',
    dangerSurface: '#fce9ea',
    focus: base.accent,
    info: base.accent,
    infoSurface: '#e8eefb',
    success: '#1d7565',
    successSurface: '#e5f1ee',
    surface: base.paper,
    surfaceMuted: '#eff4f8',
    surfaceRaised: base.white,
    text: base.ink,
    textMuted: base.inkSoft,
    warning: '#95590f',
    warningSurface: '#fbf0df',
  },
  motion: {
    micro: 180,
    press: 100,
    route: 320,
  },
  radius: {
    card: 16,
    control: 8,
    field: 12,
    pill: 999,
    sheet: 28,
  },
  space: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    6: 24,
    8: 32,
    12: 48,
    16: 64,
  },
  typography: {
    body: 17,
    bodyLineHeight: 25,
    heading: 38,
    headingLineHeight: 42,
    money: 48,
    moneyLineHeight: 52,
  },
} as const;

export type NativeTheme = keyof Pick<typeof nativeTokens, 'dark' | 'light'>;
export type NativeColorToken = keyof (typeof nativeTokens)['light'];
