import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  financeWorkspaces: defineTable({
    initialized: v.boolean(),
    subject: v.string(),
    version: v.number(),
    workspaceId: v.string(),
  }).index('by_subject', ['subject']),
  workspaceCommandReceipts: defineTable({
    idempotencyKey: v.string(),
    requestFingerprint: v.string(),
    subject: v.string(),
    workspaceId: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
  financeAccounts: defineTable({
    accountExternalId: v.string(),
    accountName: v.string(),
    lastImportedAt: v.optional(v.number()),
    sourceAsOf: v.optional(v.string()),
    state: v.union(
      v.literal('imported'),
      v.literal('manual'),
      v.literal('excluded'),
      v.literal('missing'),
    ),
    subject: v.string(),
    workspaceId: v.string(),
  }).index('by_subject_and_external_id', ['subject', 'accountExternalId']),
  importedTransactions: defineTable({
    accountId: v.id('financeAccounts'),
    aiClassification: v.optional(
      v.union(
        v.literal('discretionary'),
        v.literal('essential'),
        v.literal('transfer'),
        v.literal('refund'),
      ),
    ),
    aiConfidence: v.optional(v.number()),
    amountCents: v.number(),
    bookingDate: v.string(),
    classification: v.union(
      v.literal('unknown_debit'),
      v.literal('income'),
      v.literal('discretionary'),
      v.literal('essential'),
      v.literal('transfer'),
      v.literal('refund'),
    ),
    classificationState: v.union(v.literal('confirmed'), v.literal('review_required')),
    merchantKey: v.string(),
    sourceDescription: v.string(),
    sourceFingerprint: v.string(),
    subject: v.string(),
  })
    .index('by_subject_and_source_fingerprint', ['subject', 'sourceFingerprint'])
    .index('by_subject_and_merchant_key', ['subject', 'merchantKey']),
  merchantRules: defineTable({
    classification: v.union(
      v.literal('discretionary'),
      v.literal('essential'),
      v.literal('transfer'),
      v.literal('refund'),
    ),
    merchantKey: v.string(),
    subject: v.string(),
  }).index('by_subject_and_merchant_key', ['subject', 'merchantKey']),
  quickAdds: defineTable({
    accountId: v.id('financeAccounts'),
    amountCents: v.number(),
    bookingDate: v.string(),
    matchKey: v.string(),
    merchantKey: v.string(),
    sourceDescription: v.string(),
    state: v.union(v.literal('provisional'), v.literal('matched'), v.literal('review_required')),
    subject: v.string(),
  }).index('by_subject_and_match_key', ['subject', 'matchKey']),
  quickAddReceipts: defineTable({
    idempotencyKey: v.string(),
    quickAddId: v.id('quickAdds'),
    requestFingerprint: v.string(),
    subject: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
  deferredCardPurchases: defineTable({
    amountCents: v.number(),
    cardExternalId: v.string(),
    expectedSettlementEnd: v.string(),
    expectedSettlementStart: v.string(),
    purchaseDate: v.string(),
    purchaseExternalId: v.string(),
    remainingLiabilityCents: v.number(),
    settlementAccountExternalId: v.string(),
    sourceDescription: v.string(),
    subject: v.string(),
  }).index('by_subject_and_card_and_purchase_external_id', [
    'subject',
    'cardExternalId',
    'purchaseExternalId',
  ]),
  deferredCardSettlements: defineTable({
    amountCents: v.number(),
    cardExternalId: v.string(),
    settlementDate: v.string(),
    settlementExternalId: v.string(),
    settlementAccountExternalId: v.string(),
    sourceDescription: v.string(),
    state: v.union(v.literal('reconciled'), v.literal('review_required')),
    subject: v.string(),
    unallocatedCents: v.number(),
  }).index('by_subject_and_settlement_external_id', ['subject', 'settlementExternalId']),
  deferredCardSettlementAllocations: defineTable({
    amountCents: v.number(),
    purchaseId: v.id('deferredCardPurchases'),
    settlementId: v.id('deferredCardSettlements'),
    subject: v.string(),
  }).index('by_subject_and_settlement_id', ['subject', 'settlementId']),
  deferredCardSettlementReceipts: defineTable({
    idempotencyKey: v.string(),
    requestFingerprint: v.string(),
    result: v.object({
      outcome: v.union(v.literal('applied'), v.literal('replayed')),
      outstandingLiabilityCents: v.number(),
      settlementId: v.string(),
      state: v.union(v.literal('reconciled'), v.literal('review_required')),
    }),
    subject: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
  deferredCardPurchaseReceipts: defineTable({
    idempotencyKey: v.string(),
    purchaseId: v.id('deferredCardPurchases'),
    requestFingerprint: v.string(),
    subject: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
  goals: defineTable({
    goalExternalId: v.string(),
    label: v.string(),
    priority: v.number(),
    status: v.union(v.literal('approved'), v.literal('paused')),
    subject: v.string(),
    targetCents: v.number(),
    targetDate: v.string(),
  }).index('by_subject_and_goal_external_id', ['subject', 'goalExternalId']),
  reservations: defineTable({
    amountCents: v.number(),
    dueDate: v.string(),
    goalId: v.optional(v.id('goals')),
    kind: v.union(v.literal('goal'), v.literal('sinking_fund'), v.literal('essential')),
    label: v.string(),
    state: v.literal('approved'),
    subject: v.string(),
  }).index('by_subject_and_due_date', ['subject', 'dueDate']),
  goalCommandReceipts: defineTable({
    idempotencyKey: v.string(),
    requestFingerprint: v.string(),
    result: v.object({
      goalId: v.string(),
      outcome: v.union(v.literal('applied'), v.literal('replayed')),
      reservationId: v.string(),
    }),
    subject: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
  monthlyPlans: defineTable({
    approvedBaseDailyAllowanceCents: v.optional(v.number()),
    expectedSalaryEnd: v.string(),
    expectedSalaryStart: v.string(),
    forecastSalaryCents: v.number(),
    month: v.string(),
    proposedBaseDailyAllowanceCents: v.number(),
    receivedIncomeCents: v.optional(v.number()),
    state: v.union(
      v.literal('awaiting_approval'),
      v.literal('active'),
      v.literal('revision_proposed'),
    ),
    subject: v.string(),
    version: v.number(),
  }).index('by_subject_and_month', ['subject', 'month']),
  monthlyPlanCommandReceipts: defineTable({
    idempotencyKey: v.string(),
    requestFingerprint: v.string(),
    result: v.object({
      approvedBaseDailyAllowanceCents: v.optional(v.number()),
      month: v.string(),
      outcome: v.literal('applied'),
      planId: v.string(),
      proposedBaseDailyAllowanceCents: v.number(),
      revisionRequired: v.boolean(),
      state: v.union(
        v.literal('awaiting_approval'),
        v.literal('active'),
        v.literal('revision_proposed'),
      ),
      version: v.number(),
    }),
    subject: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
  aiUsageReservations: defineTable({
    estimatedCostNanoEur: v.number(),
    month: v.string(),
    requestFingerprint: v.string(),
    requestId: v.string(),
    state: v.union(v.literal('reserved'), v.literal('committed')),
    subject: v.string(),
    task: v.union(v.literal('routine_classification'), v.literal('monthly_planning')),
  })
    .index('by_subject_and_request_id', ['subject', 'requestId'])
    .index('by_subject_and_month_and_state', ['subject', 'month', 'state']),
  savedCsvMappings: defineTable({
    amountColumn: v.string(),
    dateColumn: v.string(),
    descriptionColumn: v.string(),
    headerSignature: v.string(),
    subject: v.string(),
  }).index('by_subject_and_header_signature', ['subject', 'headerSignature']),
  csvImportReceipts: defineTable({
    accountExternalId: v.string(),
    idempotencyKey: v.string(),
    requestFingerprint: v.string(),
    result: v.object({
      accountId: v.string(),
      importedTransactionCount: v.number(),
      outcome: v.literal('applied'),
      skippedDuplicateTransactionCount: v.number(),
      sourceAsOf: v.string(),
    }),
    subject: v.string(),
  }).index('by_subject_and_idempotency_key', ['subject', 'idempotencyKey']),
});
